// <auto-generated />
using System;
using MenuWF.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MenuWF.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230825085425_Init2")]
    partial class Init2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MenuWF.Entities.Dish", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Dishes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Салат овощной"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Борщ"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Салат Сингулярность"
                        });
                });

            modelBuilder.Entity("MenuWF.Entities.Journal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("DishWeight")
                        .HasColumnType("int");

                    b.Property<int>("RecipeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Journals");
                });

            modelBuilder.Entity("MenuWF.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Calories")
                        .HasColumnType("int");

                    b.Property<int>("Carbs")
                        .HasColumnType("int");

                    b.Property<int>("Fats")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Prots")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Calories = 50,
                            Carbs = 20,
                            Fats = 0,
                            Name = "Огурец",
                            Prots = 1
                        },
                        new
                        {
                            Id = 2,
                            Calories = 80,
                            Carbs = 15,
                            Fats = 0,
                            Name = "Картофель",
                            Prots = 2
                        },
                        new
                        {
                            Id = 3,
                            Calories = 35,
                            Carbs = 10,
                            Fats = 0,
                            Name = "Морковь",
                            Prots = 1
                        },
                        new
                        {
                            Id = 4,
                            Calories = 250,
                            Carbs = 0,
                            Fats = 15,
                            Name = "Говядина",
                            Prots = 20
                        },
                        new
                        {
                            Id = 5,
                            Calories = 130,
                            Carbs = 30,
                            Fats = 1,
                            Name = "Рис",
                            Prots = 3
                        },
                        new
                        {
                            Id = 6,
                            Calories = 70,
                            Carbs = 1,
                            Fats = 5,
                            Name = "Яйцо",
                            Prots = 6
                        },
                        new
                        {
                            Id = 7,
                            Calories = 20,
                            Carbs = 5,
                            Fats = 0,
                            Name = "Помидор",
                            Prots = 1
                        },
                        new
                        {
                            Id = 8,
                            Calories = 180,
                            Carbs = 0,
                            Fats = 10,
                            Name = "Курица",
                            Prots = 25
                        },
                        new
                        {
                            Id = 9,
                            Calories = 150,
                            Carbs = 2,
                            Fats = 15,
                            Name = "Сыр",
                            Prots = 10
                        },
                        new
                        {
                            Id = 10,
                            Calories = 40,
                            Carbs = 24,
                            Fats = 0,
                            Name = "Свекла",
                            Prots = 1
                        },
                        new
                        {
                            Id = 11,
                            Calories = 50,
                            Carbs = 26,
                            Fats = 0,
                            Name = "Капуста",
                            Prots = 1
                        },
                        new
                        {
                            Id = 12,
                            Calories = 100,
                            Carbs = 20,
                            Fats = 1,
                            Name = "Хлеб",
                            Prots = 3
                        });
                });

            modelBuilder.Entity("MenuWF.Entities.Recipe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DishId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("ProductWeight")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Recipes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DishId = 1,
                            ProductId = 1,
                            ProductWeight = 200
                        },
                        new
                        {
                            Id = 2,
                            DishId = 1,
                            ProductId = 2,
                            ProductWeight = 150
                        },
                        new
                        {
                            Id = 3,
                            DishId = 1,
                            ProductId = 3,
                            ProductWeight = 200
                        },
                        new
                        {
                            Id = 4,
                            DishId = 2,
                            ProductId = 2,
                            ProductWeight = 300
                        },
                        new
                        {
                            Id = 5,
                            DishId = 2,
                            ProductId = 3,
                            ProductWeight = 200
                        },
                        new
                        {
                            Id = 6,
                            DishId = 2,
                            ProductId = 4,
                            ProductWeight = 300
                        },
                        new
                        {
                            Id = 7,
                            DishId = 2,
                            ProductId = 7,
                            ProductWeight = 300
                        },
                        new
                        {
                            Id = 8,
                            DishId = 2,
                            ProductId = 10,
                            ProductWeight = 100
                        },
                        new
                        {
                            Id = 9,
                            DishId = 2,
                            ProductId = 11,
                            ProductWeight = 100
                        },
                        new
                        {
                            Id = 10,
                            DishId = 3,
                            ProductId = 12,
                            ProductWeight = 200
                        },
                        new
                        {
                            Id = 11,
                            DishId = 3,
                            ProductId = 5,
                            ProductWeight = 200
                        },
                        new
                        {
                            Id = 12,
                            DishId = 3,
                            ProductId = 6,
                            ProductWeight = 200
                        },
                        new
                        {
                            Id = 13,
                            DishId = 3,
                            ProductId = 8,
                            ProductWeight = 200
                        },
                        new
                        {
                            Id = 14,
                            DishId = 3,
                            ProductId = 9,
                            ProductWeight = 300
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
